# Generated by Django 4.2.1 on 2023-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(default='default_room_image.png', upload_to='images/'),
        ),
    ]
